name: MLflow CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      # === Run actions/checkout@v3 ===
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      # === Set up Python 3.12.7 ===
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # === Check Env ===
      - name: Check Env
        run: |
          python --version
          echo "SHA: $GITHUB_SHA"
          echo "Repo contents:"
          ls -R

      # === Install dependencies ===
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn==1.7.1 pandas==2.3.1 numpy==2.3.2

      # === Run mlflow project ===
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local

      # === Get latest MLflow run_id ===
      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          run_id=$(ls -td mlruns/0/*/ | head -1 | xargs basename)
          echo "RUN_ID=$run_id" >> $GITHUB_ENV
          echo "Latest run_id: $run_id"

      # === Upload to GitHub (Artifacts) ===
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model_artifacts_${{ env.RUN_ID }}
          path: |
            mlruns/0/${{ env.RUN_ID }}/artifacts/model
            mlruns/0/${{ env.RUN_ID }}/metrics/*
            mlruns/0/${{ env.RUN_ID }}/params/*

      # === Build Docker Model ===
      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            -m "mlruns/0/${{ env.RUN_ID }}/artifacts/model" \
            -n "${{ secrets.DOCKER_USERNAME }}/mlflow_model:${{ github.run_number }}"

      # === Log in to Docker Hub ===
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # === Tag Docker Image ===
      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/mlflow_model:${{ github.run_number }} \
                     ${{ secrets.DOCKER_USERNAME }}/mlflow_model:latest

      # === Push Docker Image ===
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mlflow_model:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/mlflow_model:latest